name: Python cmake build test

on:
  push:
    branches:
      - main
    tags:
      - v*
      - py_v*
  pull_request:
    branches:
      - main

jobs:
  Linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64:latest

    steps:
    - uses: actions/checkout@v4

    - name: install gfortran
      run: |
        yum install -y gcc-toolset-12.x86_64

    - name: Compile and install python bindings
      run: |
        scl enable gcc-toolset-12 bash
        /opt/python/cp311-cp311/bin/python -m pip install .

    - name: Test python bindings
      run: |
        /opt/python/cp311-cp311/bin/python -m pip install pytest
        /opt/python/cp311-cp311/bin/python -m pytest -s python/test
